name: Build ROS2 Workspace and Upload Artifact

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install ROS2 dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions python3-rosdep
        sudo rosdep init || true
        rosdep update
        rosdep install --from-paths src --ignore-src -y

    - name: Build ROS2 workspace
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon build --symlink-install

    - name: Package workspace
      run: |
        tar -czf ros2_ws.tar.gz install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ros2_ws_build
        path: ros2_ws.tar.gz
