name: Build and Push Docker Image

# main ブランチに push したときに自動実行
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - uses: actions/checkout@v3

      # Docker Buildx をセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # GitHub Container Registry にログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker イメージをビルドして push
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/rrst-nhk-project/rrst-ros2-ws-docker:latest

      # （オプション）最新のコミット SHA をタグとして追加
      - name: Tag image with SHA
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/rrst-nhk-project/rrst-ros2-ws-docker:${{ github.sha }}
